language: node_js

env:
  global:
  - SBT_VER=1.3.13
  - TRAVIS_JDK=zulu@1.8.252

addons:
  homebrew:
    packages:
      - clang-format

matrix:
  include:
   - scala: 2.12.12
     os: osx
     env:
       CMD="checkFormat filesJVM/jacoco filesJS/test filesJVM/travisQuickListReflectionTest filesJVM/allTests"
       TRAVIS_SCALA_VERSION=2.12.12
     osx_image: xcode9.4

   - scala: 2.12.12
     env:
       CMD="filesJVM/jacoco filesJS/test filesJVM/travisQuickListReflectionTest filesJVM/allTests"
       TRAVIS_SCALA_VERSION=2.12.12


script: /tmp/sbt/bin/sbt -Dswoval.alltest.timeout=20 -Dswoval.format=false -Dsbt.version=$SBT_VER -Dswoval.skip.native=true -Dswoval.fork.tests=true -Dswoval.alltests.iterations=50 ++$TRAVIS_SCALA_VERSION $CMD

before_install:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
  - unset _JAVA_OPTIONS;
  - wget https://github.com/sbt/sbt/releases/download/v1.3.13/sbt-1.3.13.tgz
  - tar -xvf sbt-1.3.13.tgz
  - rm sbt-1.3.13.tgz
  - mv sbt /tmp/sbt
  - npm install -g cmake-js;
  - curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
  - jabba install $TRAVIS_JDK
  - unset _JAVA_OPTIONS
  - export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/Library/Caches/Homebrew

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
